import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ganache from 'ganache';
import { BrowserProvider, ContractFactory } from 'ethers';
import { readCatalog, verifyReceipt } from '../lib/launch/catalog.js';
const artifact=JSON.parse(readFileSync('assets/launch/test-token.json'));
const chain=ganache.provider({logging:{quiet:true},chain:{chainId:46630,hardfork:'shanghai'}});
const provider=new BrowserProvider(chain);provider.pollingInterval=10;
const signer=await provider.getSigner();
const token=await new ContractFactory(artifact.abi,artifact.bytecode,signer).deploy('PUBLIC TEST','PUB','Public test only','https://example.com/dot.webp','','blue');
const receipt=await token.deploymentTransaction().wait();await chain.request({method:'evm_mine',params:[]});
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{const request=JSON.parse(options.body);try{return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:await chain.request({method:request.method,params:request.params})})}}catch(e){return {ok:true,json:async()=>({error:{message:e.message}})}}};
const catalog=await readCatalog();assert.equal(catalog.launches.length,1);assert.equal(catalog.launches[0].address.toLowerCase(),(await token.getAddress()).toLowerCase());assert.equal(catalog.launches[0].dot,'blue');assert.equal(catalog.launches[0].chainId,46630);
const verified=await verifyReceipt(receipt.hash);assert.equal(verified.pending,false);assert.equal(verified.launch.symbol,'PUB');
const pending=await verifyReceipt('0x'+'a'.repeat(64));assert.equal(pending.pending,true);
const transfer=await token.transfer(await signer.getAddress(),0);const tr=await transfer.wait();await chain.request({method:'evm_mine',params:[]});await assert.rejects(verifyReceipt(tr.hash),/not a token deployment/);
globalThis.fetch=async()=>({ok:true,json:async()=>({result:'0x123'})});await assert.rejects(readCatalog(),/wrong chain/);
globalThis.fetch=originalFetch;await chain.disconnect();console.log('PASS: public blockchain discovery, receipt verification, pending handling, unrelated transaction and wrong-chain rejection');
