create table if not exists public.desk_runs (
  id bigint generated by default as identity primary key,
  ticker text not null,
  reference_price numeric not null,
  market_timestamp timestamptz not null,
  consensus text not null check (consensus in ('LONG','SHORT','WAIT')),
  consensus_confidence numeric not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_calls (
  id bigint generated by default as identity primary key,
  desk_run_id bigint not null references public.desk_runs(id) on delete cascade,
  agent_id text not null,
  agent_name text not null,
  bias text not null check (bias in ('LONG','SHORT','WAIT')),
  confidence numeric not null,
  reasons jsonb not null,
  risks jsonb not null,
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.call_results (
  id bigint generated by default as identity primary key,
  desk_run_id bigint not null references public.desk_runs(id) on delete cascade,
  horizon text not null check (horizon in ('1H','1D','1W')),
  observed_price numeric,
  return_pct numeric,
  resolved boolean not null default false,
  observed_at timestamptz,
  unique(desk_run_id,horizon)
);

create index if not exists idx_desk_runs_ticker_created on public.desk_runs(ticker,created_at desc);
create index if not exists idx_agent_calls_agent_created on public.agent_calls(agent_id,created_at desc);

alter table public.desk_runs enable row level security;
alter table public.agent_calls enable row level security;
alter table public.call_results enable row level security;
